---
label: Project
hide_body: false
fields:
- type: text
  name: LingDao
  label: LingDao
  description: Massage TuiNa, méditation et dessin libre
  hidden: true
- type: text
  name: Massage_TuiNa__meditation_et_dessin_libre
  description: LingDao propose du massage TuiNa inspiré des principes de la médecine
    traditionnelle chinoise et un atelier de méditation et dessin libre
  label: Massage TuiNa, méditation et dessin libre
- type: file
  name: image
  label: image
- type: file
  name: bg_image
  label: bg image
  description: page header background image
- type: text
  name: category
  label: category
  description: Filter Category
- type: field_group_list
  name: information
  label: information
  fields:
  - type: text
    name: label
    label: label
  - type: text
    name: info
    label: info
